version: "3.8"

services:
  python-backend:
    build:
      context: ./services/python-backend
      dockerfile: Dockerfile
    container_name: python-backend
    volumes:
      - ./services/python-backend/:/src
    ports:
      - "8000:8000"
    env_file:
      - ./services/python-backend/.env
    networks:
      - default

networks:
  default:
