version: "3.8"

services:
  python-backend:
    build:
      context: ./services/python-backend
      dockerfile: Dockerfile
    container_name: python-backend
    volumes:
      - ./services/python-backend/:/src
    ports:
      - "8000:8000"
    env_file:
      - ./services/python-backend/.env
    networks:
      - default

  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./services/frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    networks:
      - default

networks:
  default:
